---
name: terraform-enterprise
services:
  tfe:
    image: images.releases.hashicorp.com/hashicorp/terraform-enterprise:v202309-1
    environment:
      TFE_LICENSE: "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JLFVE252ZK5HG2TKEKF2E4RCONRHUGMBVJVDVCM2MKRVTCT2EM52FS2SJPJGTEVTMJV5FSNCNNVHG2SLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJJWE2VCNGJHFOTTKJVUTC2C2NJWGWTCUJE2U4VCBORGUITJVJVUTC3C2NJMTETTNKEYFSVCNO5MXUQLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SNORGUI23UJVKEUVKNIRTTMTLKLE3E4VCBOVGWURLYJVKFCMKOIRRXSV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJPJGFIQJVJRKEK6KWIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKKV2E2RCFORGUIRSVJVCECNSNIRATMTKEIJQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJKXITKEIV2E2RCGKVGUIQJWJVCECNSNIRBGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNZJGYY3OJJUFU3JZPFRFGSLTJFWVU42ZK5SHUSLKOA3WMWBQHUXGCQ3SM5MXA32VPB3GQTTJJJYFU2ZSKVMDO5DMKZBWOOJUIUVUCSRSJYYHU4LMOVSWS3LRPFLDIVDPF5EES3CFNYXUWTTFMR4WW4ZQNFEDCUSEGJVWMTKOMMYE4YJQINVXUSKEI5BDKMLEIFVWGYJUMRLDAMZTHBIHO3KWNRQXMSSQGRYEU6CJJE4UINSVIZGFKYKWKBVGWV2KORRUINTQMFWDM32PMZDW4SZSPJIEWSSSNVDUQVRTMVNHO4KGMUVW6N3LF5ZSWQKUJZUFAWTHKMXUWVSZM4XUWK3MI5IHOTBXNJBHQSJXI5HWC2ZWKVQWSYKIN5SWWMCSKRXTOMSEKE6T2"
      TFE_HOSTNAME: dmitry-fdo-test.tf-support.hashicorpdemo.com
      TFE_ENCRYPTION_PASSWORD: "Password1#"
      TFE_OPERATIONAL_MODE: "external"
      TFE_DISK_CACHE_VOLUME_NAME: ${COMPOSE_PROJECT_NAME}_terraform-enterprise-cache
      TFE_TLS_CERT_FILE: /etc/ssl/private/terraform-enterprise/cert.pem
      TFE_TLS_KEY_FILE: /etc/ssl/private/terraform-enterprise/key.pem
      TFE_TLS_CA_BUNDLE_FILE: /etc/ssl/private/terraform-enterprise/bundle.pem
      TFE_IACT_SUBNETS: 0.0.0.0/0

      # Database settings
      TFE_DATABASE_USER: "postgres"
      TFE_DATABASE_PASSWORD: "Password1#"
      TFE_DATABASE_HOST: "dmitry-fdo-test-postgres.cheg1b8bnf4j.eu-west-2.rds.amazonaws.com"
      TFE_DATABASE_NAME: "fdo"
      TFE_DATABASE_PARAMETERS: "sslmode=disable"

      # Object storage settings
      TFE_OBJECT_STORAGE_TYPE: "s3"
      TFE_OBJECT_STORAGE_S3_REGION: "eu-west-2"
      TFE_OBJECT_STORAGE_S3_BUCKET: "dmitry-fdo-test-bucket"
      TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE: "true"
    cap_add:
      - IPC_LOCK
    read_only: true
    tmpfs:
      - /tmp:mode=01777
      - /run
      - /var/log/terraform-enterprise
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /run/docker.sock
      - type: bind
        source: ./certs
        target: /etc/ssl/private/terraform-enterprise
      - type: volume
        source: terraform-enterprise-cache
        target: /var/cache/tfe-task-worker/terraform
volumes:
  terraform-enterprise-cache:     